name: Reg_Shiny
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - r-base>=4.3
  - r-shiny>=1.8.1
  - r-bslib>=0.7
  - r-dt
  - r-data.table
  - r-processx
  - r-future
  - r-promises
  - r-jsonlite
  - samtools>=1.20
  - bcftools>=1.20
  - regtools=1.0.0
